package hardcoder.dev.android_app.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF506601)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD2EE80)
val md_theme_light_onPrimaryContainer = Color(0xFF161F00)
val md_theme_light_secondary = Color(0xFF116D34)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF9FF6AE)
val md_theme_light_onSecondaryContainer = Color(0xFF00210A)
val md_theme_light_tertiary = Color(0xFF3A665E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCECE2)
val md_theme_light_onTertiaryContainer = Color(0xFF00201C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFEFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE3E4D3)
val md_theme_light_onSurfaceVariant = Color(0xFF46483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFF3F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312C)
val md_theme_light_inversePrimary = Color(0xFFB6D168)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF506601)
val md_theme_light_outlineVariant = Color(0xFFC6C8B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB6D168)
val md_theme_dark_onPrimary = Color(0xFF283500)
val md_theme_dark_primaryContainer = Color(0xFF3C4D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFD2EE80)
val md_theme_dark_secondary = Color(0xFF84D994)
val md_theme_dark_onSecondary = Color(0xFF003917)
val md_theme_dark_secondaryContainer = Color(0xFF005224)
val md_theme_dark_onSecondaryContainer = Color(0xFF9FF6AE)
val md_theme_dark_tertiary = Color(0xFFA1D0C6)
val md_theme_dark_onTertiary = Color(0xFF033731)
val md_theme_dark_tertiaryContainer = Color(0xFF204E47)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCECE2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF46483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C17)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF506601)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB6D168)
val md_theme_dark_outlineVariant = Color(0xFF46483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF506601)